<html>
 <head></head>
 <body>
  <p>A lot of things can go wrong when you try to read and write files. If you try to open a file that doesn’t exist, you get an <span class="math-tex">\( IOError \)</span>:&nbsp;<br></p>
  <pre><code class="language-python">&gt;&gt;&gt;&nbsp;fin&nbsp;=&nbsp;open('bad_file')
IOError:&nbsp;[Errno 2]&nbsp;No&nbsp;such&nbsp;file&nbsp;or&nbsp;directory:&nbsp;'bad_file'</code></pre>
  <p><br>If you don’t have permission to access a file:&nbsp;<br></p>
  <pre><code class="language-python">&gt;&gt;&gt; fin = open('/etc/passwd', 'w')
IOError: [Errno 13] Permission&nbsp;denied:&nbsp;'/etc/passwd'</code></pre>
  <p><br>And if you try to open a directory for reading, you get&nbsp;<br></p>
  <pre><code class="language-python">&gt;&gt;&gt; fin = open('/home')
IOError: [Errno 21] Is&nbsp;a&nbsp;directory</code></pre>
  <p><br>To avoid these errors, you could use functions like <span class="math-tex">\( os.path.exists \)</span>&nbsp;and <span class="math-tex">\( os.path.isfile \)</span>, but it would take a lot of time and code to check all the possibilities (if “<span class="math-tex">\( Errno 21 \)</span>” is any indication, there are at least 21 things that can go wrong).&nbsp;<br>It is better to go ahead and try—and deal with problems if they happen—which is exactly what the <span class="math-tex">\( try \)</span>&nbsp;statement does. The syntax is similar to an <span class="math-tex">\( if \)</span>&nbsp;statement:&nbsp;<br></p>
  <pre><code class="language-python">try:
    fin&nbsp;=&nbsp;open('bad_file')
    for&nbsp;line&nbsp;in&nbsp;fin:
       print(line)
    fin.close()
except:
    print('Something went wrong.')</code></pre>
  <p><br>Python starts by executing the <span class="math-tex">\( try \)</span> clause. If all goes well, it skips the <span class="math-tex">\( except \)</span>&nbsp;clause and proceeds. If an exception occurs, it jumps out of the <span class="math-tex">\( try \)</span> clause and executes the <span class="math-tex">\( except \)</span>&nbsp;clause.&nbsp;<br>Handling an exception with a <span class="math-tex">\( try \)</span> statement is called catching an exception. In this example, the <span class="math-tex">\( except \)</span> clause prints an error message that is not very helpful. In general, catching an exception gives you a chance to fix the problem, or try again, or at least end the program gracefully.&nbsp;</p>
  <p style="text-align: right;">[Think Python by Allen B. Downey] <br><br></p>
  <p style="text-align: left;">﻿See&nbsp;more&nbsp;here:<br><a href="https://docs.python.org/3.3/tutorial/errors.html" rel="nofollow noopener noreferrer" title="Link: https://docs.python.org/3.3/tutorial/errors.html">https://docs.python.org/3.3/tutorial/errors.html</a><br><a href="https://en.wikipedia.org/wiki/Exception_handling" rel="nofollow noopener noreferrer" title="Link: https://en.wikipedia.org/wiki/Exception_handling">https://en.wikipedia.org/wiki/Exception_handling</a><br></p>
 </body>
</html>